language: python

#defualting to trusty instead of precise (Ubuntu 14.04 LTS)
dist: trusty

# Use containers instead of full VMs for faster startup.
sudo: false

python:
  - 2.7
  - 3.6

install:
  - pip install -r requirements.txt
script: python setup.py